from __future__ import annotations

# Each entry contains: number, chapter_id, part, slug, title, maturity,
# and five semantic sections expressed as heading plus verified-scope note.

SPECS_14_45 = [
    (14, "CH-P03-RL", "P03", "14_reinforcement_learning", "Reinforcement learning", "CORE", [
        ("Dalle predizioni alle azioni", "Un agente osserva uno stato, sceglie un'azione e riceve un reward. Il dato centrale non è una label statica, ma una traiettoria prodotta dall'interazione."),
        ("MDP e ritorno", "Un Markov Decision Process specifica stati, azioni, transizioni, reward e fattore di sconto. Il ritorno somma reward futuri pesati e dipende dalla policy seguita."),
        ("Value function e Bellman", "La value function riassume il ritorno atteso. Le equazioni di Bellman collegano il valore corrente a reward immediato e valore degli stati successivi."),
        ("Policy gradient e actor-critic", "Il policy gradient aggiorna direttamente una policy stocastica. Actor-critic combina una policy con una stima di valore che riduce la varianza del segnale."),
        ("Esplorazione e valutazione", "Esplorare significa raccogliere informazione su azioni non ancora ben valutate. Una policy deve essere misurata su ritorno, varianza, sicurezza e condizioni dell'ambiente."),
    ]),
    (15, "CH-P04-MLP", "P04", "15_mlp", "Dal percettrone alle reti multilayer", "CORE", [
        ("Una decisione lineare", "Il percettrone combina feature con pesi e bias. Il confine risultante è lineare nello spazio delle feature."),
        ("Strati nascosti", "Una MLP alterna trasformazioni affini e funzioni non lineari. Senza non linearità, più layer affini collassano in una sola trasformazione affine."),
        ("Attivazioni", "ReLU, tanh, sigmoid e GELU modificano propagazione, saturazione e regolarità. La scelta deve essere letta insieme a inizializzazione e normalizzazione."),
        ("Capacità ed espressività", "Una rete più ampia può rappresentare funzioni più complesse, ma parametri aggiuntivi non garantiscono generalizzazione o ottimizzazione stabile."),
        ("Dal forward al training", "Il forward produce logits e loss. Backpropagation e optimizer trasformano il segnale in aggiornamenti, secondo i contratti costruiti nei capitoli matematici."),
    ]),
    (16, "CH-P04-DEEP-TRAINING", "P04", "16_deep_training", "Addestrare reti profonde", "CORE", [
        ("Segnali che attraversano molti layer", "Attivazioni e gradienti possono crescere o ridursi lungo la profondità. Inizializzazione, attivazioni e residual determinano la scala osservata."),
        ("Inizializzazione", "Xavier e He initialization collegano la varianza dei pesi al fan-in o fan-out. Le formule presuppongono attivazioni e indipendenze approssimate."),
        ("Normalizzazione", "BatchNorm, LayerNorm e RMSNorm normalizzano assi e statistiche differenti. Non sono sostituibili senza considerare batch, sequenza e architettura."),
        ("Residual e profondità", "Un residual path conserva un percorso identità e facilita il trasporto di informazione. La somma richiede shape compatibili e una scala controllata."),
        ("Regolarizzazione e diagnostica", "Dropout, weight decay, data augmentation ed early stopping agiscono in punti diversi. Curve, norme e slice aiutano a distinguere underfitting, overfitting e instabilità."),
    ]),
    (17, "CH-P04-CNN-GEOMETRIC", "P04", "17_cnn_geometric", "Convolutional network e apprendimento geometrico", "CORE", [
        ("Condivisione locale dei pesi", "Una convoluzione applica lo stesso kernel in posizioni differenti. Questa condivisione incorpora una ipotesi di regolarità locale."),
        ("Stride, padding e receptive field", "Stride e padding determinano la griglia dell'output. Il receptive field cresce con layer, kernel e dilatazione."),
        ("Equivarianza e invariance", "La convoluzione è equivariant a traslazioni entro le condizioni del bordo. Pooling e aggregazione possono costruire una maggiore invariance."),
        ("Vision Transformer e ibridi", "Patch embedding e attention offrono una geometria diversa. CNN e Transformer possono essere combinati, ma il confronto richiede stesso budget e dati."),
        ("Grafi e message passing", "Su un grafo, i vicini non sono disposti in una griglia regolare. Le GNN aggregano messaggi rispettando la struttura degli archi e le simmetrie dichiarate."),
    ]),
    (18, "CH-P04-RECURRENT", "P04", "18_recurrent", "Reti ricorrenti e modelli sequenziali", "CORE", [
        ("Uno stato che attraversa la sequenza", "Una RNN aggiorna uno stato nascosto con input e stato precedente. Lo stesso insieme di parametri viene riutilizzato a ogni passo."),
        ("Backpropagation through time", "Il grafo ricorrente viene srotolato nel tempo. Gradienti molto lunghi possono svanire o esplodere."),
        ("LSTM e GRU", "Gate di input, forget e output controllano il flusso della memoria. GRU usa una parametrizzazione più compatta, con un contratto differente."),
        ("Bidirezionalità e causalità", "Una rete bidirezionale usa anche il futuro ed è adatta a encoding offline. Non può essere usata direttamente per generazione causale streaming."),
        ("RNN, attention e stato", "La recurrence mantiene memoria compatta; l'attention accede a rappresentazioni esplicite. I due meccanismi possono essere complementari."),
    ]),
    (19, "CH-P04-REPRESENTATION", "P04", "19_representation_learning", "Representation learning", "CORE", [
        ("Che cosa rappresenta un vettore", "Una rappresentazione è un insieme di quantità prodotte dal modello e usate da un calcolo successivo. Il significato dipende da obiettivo e dati."),
        ("Bottleneck e autoencoder", "Un autoencoder comprime e ricostruisce. Un bottleneck limita la capacità, ma non garantisce che le coordinate corrispondano a fattori interpretabili."),
        ("Metric e contrastive learning", "Obiettivi contrastivi avvicinano coppie positive e separano alternative. La definizione delle coppie e delle augmentazioni stabilisce le invarianti apprese."),
        ("Disentanglement e identifiability", "Separare fattori latenti richiede ipotesi. Senza supervision o bias aggiuntivi, molte rappresentazioni equivalenti possono spiegare gli stessi dati."),
        ("Valutare una rappresentazione", "Linear probe, retrieval e fine-tuning misurano proprietà diverse. Una buona metrica downstream non dimostra interpretabilità globale."),
    ]),
    (20, "CH-P05-GENERATIVE-FOUNDATIONS", "P05", "20_generative_foundations", "Fondamenti della modellazione generativa", "CORE", [
        ("Imparare una distribuzione", "Un modello generativo descrive o campiona dati secondo una distribuzione. Densità, likelihood e sampling sono contratti distinti."),
        ("Modelli espliciti e impliciti", "Un modello esplicito assegna una densità o probabilità valutabile. Un modello implicito definisce il campionamento senza una likelihood semplice."),
        ("Variabili latenti", "Una variabile latente introduce struttura non osservata. L'inferenza deve collegare dati e latenti, esattamente o mediante approssimazione."),
        ("Energy-based model", "Una energia non normalizzata assegna punteggi alle configurazioni. La costante di partizione rende difficile la likelihood in molti casi."),
        ("Qualità, copertura e valutazione", "Campioni plausibili non garantiscono copertura. Likelihood e precision-recall generativa rispondono a domande diverse e richiedono protocolli dichiarati."),
    ]),
    (21, "CH-P05-AUTOREGRESSIVE", "P05", "21_autoregressive", "Modelli autoregressivi", "CORE", [
        ("Fattorizzare una sequenza", "La chain rule scompone la probabilità con un ordine. Ogni fattore condiziona sugli elementi precedenti."),
        ("Teacher forcing", "Durante il training il modello riceve il prefisso reale e predice il passo successivo. Durante la generazione riceve anche i propri output."),
        ("Maschera causale", "La causal mask impedisce a una posizione di usare target futuri. Un errore nella maschera produce leakage pur con loss numericamente valida."),
        ("Sampling e accumulo degli errori", "Ogni scelta modifica il contesto successivo. Errori iniziali possono spostare la traiettoria verso regioni poco viste nel training."),
        ("Immagini, audio e token discreti", "L'autoregressione non è limitata al testo. Una sequenza può rappresentare pixel, code audio o latent discreti."),
    ]),
    (22, "CH-P05-VAE-VQ", "P05", "22_vae_vq", "Variational Autoencoder e latent discreti", "CORE", [
        ("Inferenza approssimata", "Il VAE introduce un encoder q(z|x) per approssimare il posterior. Il decoder modella p(x|z)."),
        ("ELBO", "L'evidence lower bound combina ricostruzione e KL verso il prior. Massimizzare l'ELBO non coincide necessariamente con massimizzare qualità percettiva."),
        ("Reparameterization trick", "Un campione gaussiano viene scritto come trasformazione di rumore indipendente. Questo consente gradienti pathwise."),
        ("Posterior collapse", "Un decoder molto potente può ignorare z e avvicinare il posterior al prior. KL annealing e architettura possono modificare il fenomeno."),
        ("VQ-VAE", "La quantizzazione vettoriale sostituisce il latent continuo con indici di un codebook. Commitment loss e aggiornamento del codebook richiedono controlli dedicati."),
    ]),
    (23, "CH-P05-GAN", "P05", "23_gan", "Generative Adversarial Network", "CORE", [
        ("Un gioco tra due modelli", "Il generatore produce campioni; il discriminatore distingue dati reali e generati. L'obiettivo è un gioco, non una loss singola ottimizzata congiuntamente."),
        ("Divergenze e gradienti", "La formulazione originale è collegata alla Jensen-Shannon divergence sotto un discriminatore ottimo. I gradienti pratici dipendono dalla loss scelta."),
        ("Mode collapse", "Il generatore può produrre poche modalità convincenti. Diversità e fedeltà devono essere misurate separatamente."),
        ("Wasserstein GAN", "WGAN usa una distanza legata a funzioni Lipschitz. Weight clipping e gradient penalty sono implementazioni differenti del vincolo."),
        ("Stabilità e valutazione", "Bilanciare update, normalizzazioni e capacità è essenziale. FID è una metrica su feature e non sostituisce l'analisi dei campioni."),
    ]),
    (24, "CH-P05-FLOWS", "P05", "24_normalizing_flows", "Normalizing flow e trasformazioni invertibili", "ESTABLISHED", [
        ("Cambio di variabile", "Una trasformazione invertibile collega una distribuzione semplice ai dati. La densità usa il determinante Jacobiano."),
        ("Coupling layer", "RealNVP e Glow costruiscono trasformazioni triangolari, con inversa e log-determinante efficienti."),
        ("Invertibilità e architettura", "L'invertibilità limita operazioni e dimensioni. Squeeze, split e permutazioni riorganizzano l'informazione senza perderla."),
        ("Continuous normalizing flow", "Una ODE definisce una trasformazione continua. La likelihood usa la variazione del log-density lungo il flusso."),
        ("Sampling e costo", "I flow offrono likelihood e campionamento esatto rispetto al modello, ma possono richiedere molte trasformazioni o solve numerici."),
    ]),
    (25, "CH-P05-DIFFUSION-FLOW", "P05", "25_diffusion_flow", "Diffusione, score matching e flow matching", "CORE", [
        ("Corrompere e ricostruire", "La diffusione forward aggiunge rumore secondo uno schedule. Il modello impara a invertire o a stimare una quantità equivalente."),
        ("Score matching", "Lo score è il gradiente del log-density rispetto ai dati perturbati. Denoising score matching evita di conoscere la densità normale completa."),
        ("Parametrizzazioni epsilon, x0 e v", "Target differenti sono trasformazioni della stessa relazione sotto uno schedule, ma cambiano scala e weighting del training."),
        ("Sampler", "DDPM, DDIM e solver ODE/SDE usano discretizzazioni differenti. Meno step non garantiscono stessa distribuzione o qualità."),
        ("Flow matching e rectified flow", "Flow matching apprende un campo vettoriale lungo percorsi scelti tra distribuzioni. Rectified flow cerca traiettorie più rettilinee in setup specifici."),
    ]),
    (26, "CH-P06-TEXT-DATA", "P06", "26_text_data", "Il testo come dato", "CORE", [
        ("Unicode e byte", "Il testo è una sequenza di code point codificata in byte. Normalizzazione Unicode e decoding devono essere dichiarati."),
        ("Tokenizzazione", "BPE, WordPiece e Unigram costruiscono vocabolari subword con algoritmi differenti. Il tokenizer fa parte dell'interfaccia del checkpoint."),
        ("Token speciali", "BOS, EOS, padding, separatori e marker di ruolo hanno significati operativi. ID uguali richiedono la stessa convenzione."),
        ("Packing e confini", "Più documenti possono condividere una sequenza. Attention mask e loss mask devono impedire dipendenze non desiderate."),
        ("Lunghezza, lingua e costi", "Token per carattere variano tra lingue e formati. La lunghezza in token influenza contesto, costo e valutazione."),
    ]),
    (27, "CH-P06-EMBEDDINGS", "P06", "27_embeddings", "Embedding e spazio semantico", "CORE", [
        ("Da ID a vettore", "Una embedding table seleziona una riga per token. La dimensione del vettore è una scelta architetturale."),
        ("Word embedding", "Word2vec e GloVe usano statistiche distributive con obiettivi differenti. Similarità geometrica riflette dati e obiettivo."),
        ("Embedding contestuale", "In un Transformer, la rappresentazione di un token cambia con il contesto. La stessa stringa può produrre vettori diversi."),
        ("Sentence embedding", "Pooling o training contrastivo producono vettori per frasi e documenti. La metrica deve corrispondere all'uso previsto."),
        ("Ricerca e anisotropia", "Cosine similarity è una convenzione, non una misura universale di significato. Normalizzazione e distribuzione dello spazio influenzano il ranking."),
    ]),
    (29, "CH-P06-TRANSFORMER", "P06", "29_transformer", "Il Transformer da zero", "CORE", [
        ("La mappa completa", "Il Transformer combina embedding, posizione, attention, feed-forward, residual e normalizzazione. Ogni componente mantiene un contratto di shape."),
        ("Encoder", "L'encoder usa self-attention bidirezionale e produce rappresentazioni per tutte le posizioni."),
        ("Decoder", "Il decoder usa self-attention causale e, nelle architetture encoder-decoder, cross-attention verso l'encoder."),
        ("Multi-head attention", "Le head applicano proiezioni differenti e vengono concatenate. La proiezione finale riporta alla dimensione del modello."),
        ("Residual stream e output", "Layer ripetuti aggiornano il residual stream. La head di output trasforma la rappresentazione in logits sul vocabolario."),
    ]),
    (30, "CH-P06-PRETRAIN-FAMILIES", "P06", "30_pretraining_families", "Famiglie architetturali e obiettivi di pretraining", "CORE", [
        ("Encoder-only", "Modelli come BERT usano contesto bidirezionale e obiettivi masked. Sono naturali per encoding e classificazione."),
        ("Decoder-only", "Un decoder causale predice token successivi e supporta generazione incrementale."),
        ("Encoder-decoder", "T5 e famiglie affini trasformano una sequenza sorgente in una sequenza target con cross-attention."),
        ("Masked, causal e span corruption", "Obiettivi differenti stabiliscono quali token sono visibili e quali producono loss."),
        ("Architettura e obiettivo", "La forma del modello e l'obiettivo sono assi separati. Confrontarli richiede dati, compute e task coerenti."),
    ]),
    (31, "CH-P06-LLM-BEHAVIOR", "P06", "31_llm_behavior", "Dalla rappresentazione linguistica agli LLM", "CORE", [
        ("Distribuzione del token successivo", "Un LLM autoregressivo produce logits condizionati sul prefisso. La softmax costruisce una distribuzione, non una risposta già scelta."),
        ("Prompt e dimostrazioni", "Istruzioni ed esempi entrano nel contesto senza un optimizer step. Il checkpoint resta invariato durante in-context learning."),
        ("Decoding", "Greedy, sampling, temperature e truncation trasformano la distribuzione in una traiettoria."),
        ("Calibrazione", "Probabilità del token, confidenza espressa e correttezza fattuale sono quantità differenti."),
        ("Modello e sistema", "Post-training, messaggi di sistema, strumenti e filtri contribuiscono al comportamento osservato."),
    ]),
    (32, "CH-P07-DATA-LIFECYCLE", "P07", "32_data_lifecycle", "Il ciclo di vita dei dati", "CORE", [
        ("Sorgenti e provenienza", "Record, documenti, timestamp e licenze devono restare tracciabili dalla raccolta allo shard."),
        ("Parsing e normalizzazione", "Trasformazioni di HTML, PDF, codice e conversazioni possono perdere informazione e devono essere versionate."),
        ("Filtri", "Filtri di qualità, lingua, sicurezza e PII modificano la distribuzione e richiedono statistiche prima e dopo."),
        ("Deduplicazione e contaminazione", "Hash esatti e similarità approssimata rilevano forme differenti di duplicazione. I benchmark richiedono controlli separati."),
        ("Split, tokenizzazione e manifest", "Confini temporali, tokenizer, packing, checksum e conteggi definiscono l'artefatto usato dal training."),
    ]),
    (33, "CH-P07-DATA-MIXTURE", "P07", "33_data_mixture", "Dataset mixture, curriculum e dati sintetici", "ESTABLISHED", [
        ("Peso effettivo delle sorgenti", "Dimensione grezza, probabilità di campionamento e ripetizione determinano le esposizioni."),
        ("Temperature sampling", "Un esponente sulle proporzioni aumenta o riduce il peso relativo dei domini piccoli."),
        ("Mixture ottimizzata", "Pesi appresi con proxy model dipendono da domini, validation e budget."),
        ("Curriculum", "Cambiare ordine e difficoltà nel tempo modifica la traiettoria di ottimizzazione."),
        ("Dati sintetici", "Modello generatore, prompt, filtri e provenienza devono essere registrati per evitare feedback non controllato."),
    ]),
    (34, "CH-P07-SCALING", "P07", "34_scaling_laws", "Scaling law e progettazione del modello", "CORE", [
        ("Fit empirico", "Una power law approssima loss rispetto a parametri, dati o compute in un intervallo misurato."),
        ("Allocazione compute-optimal", "A budget fissato, modello e token competono. Il risultato dipende da ricetta e qualità dei dati."),
        ("Esperimenti isoFLOP", "Configurazioni con compute simile rendono osservabile la loss minima per budget."),
        ("Extrapolation", "Residui, intervalli e ipotesi su loss irriducibile limitano la previsione fuori scala."),
        ("Training e inference cost", "Una scelta compute-optimal per il training può non minimizzare costo e latenza del servizio."),
    ]),
    (35, "CH-P07-PRETRAIN-RECIPE", "P07", "35_pretraining_recipe", "La ricetta di pretraining", "CORE", [
        ("Batch di token", "Packing, padding e mask determinano quanti token validi contribuiscono alla loss."),
        ("Inizializzazione", "Scala dei pesi e residual deve restare coerente con profondità, norm e dtype."),
        ("AdamW", "Learning rate, beta, epsilon e weight decay descrivono insieme l'optimizer."),
        ("Warmup e schedule", "Il learning rate dipende da step o token e deve riprendere dal contatore corretto."),
        ("Checkpoint e recovery", "Modello, optimizer, scheduler, scaler, RNG e posizione nei dati servono per un resume fedele."),
    ]),
    (36, "CH-P07-DISTRIBUTED-TRAINING", "P07", "36_distributed_training", "Training distribuito e continued pretraining", "CORE", [
        ("Data parallelism", "Repliche elaborano sotto-batch e aggregano gradienti. Media e loss reduction devono essere coerenti."),
        ("ZeRO e FSDP", "Parametri, gradienti e optimizer state vengono shardati tra worker."),
        ("Tensor e pipeline parallelism", "Matrici o gruppi di layer vengono divisi, introducendo collective e microbatch."),
        ("Topologia e fault tolerance", "Banda, latenza, checkpoint e cursor dei dati diventano parte della ricetta."),
        ("Continued pretraining", "Un checkpoint viene adattato a nuovi dati con learning rate, mixture e valutazioni di regressione dichiarate."),
    ]),
    (37, "CH-P08-MODERN-BLOCK", "P08", "37_modern_block", "Anatomia del blocco moderno", "CORE", [
        ("Residual stream", "Ogni sottolayer produce un aggiornamento sommato a un percorso identità."),
        ("Pre-norm e post-norm", "La posizione della normalizzazione cambia il percorso dei gradienti e il contratto del blocco."),
        ("RMSNorm", "RMSNorm scala usando la media quadratica e non sottrae la media."),
        ("SwiGLU", "Due proiezioni di ingresso costruiscono un gate moltiplicativo prima della proiezione down."),
        ("Ordine e parallelismo", "Attention e MLP possono essere sequenziali o paralleli; il nome del modello non basta a ricostruire l'ordine."),
    ]),
    (38, "CH-P08-POSITION-CONTEXT", "P08", "38_position_context", "Posizione e contesto lungo", "CORE", [
        ("Posizione assoluta", "Embedding appresi o sinusoidali aggiungono un segnale legato all'indice."),
        ("Posizione relativa", "Bias o rappresentazioni relative modificano i confronti in funzione della distanza."),
        ("RoPE", "Rotazioni di query e key rendono il prodotto scalare dipendente dall'offset relativo."),
        ("ALiBi", "Bias lineari penalizzano distanze maggiori con slope per head."),
        ("Estensione e valutazione", "Positional interpolation e metodi affini estendono gli indici, ma l'uso effettivo del contesto deve essere misurato."),
    ]),
    (39, "CH-P08-ATTENTION-KV", "P08", "39_attention_kv", "Varianti dell'attention e gestione KV", "CORE", [
        ("MHA", "Ogni query head possiede key e value dedicate."),
        ("MQA", "Tutte le query head condividono una singola coppia key-value, riducendo la cache."),
        ("GQA", "Gruppi di query head condividono un numero intermedio di KV head."),
        ("Local e sparse attention", "Finestre e pattern selezionati riducono le coppie ma cambiano la connettività."),
        ("MLA e cache", "Compressione latente e numero di KV head sono strategie differenti. La memoria dipende anche da layer, dtype, batch e lunghezza."),
    ]),
    (40, "CH-P08-HARDWARE-AWARE-ATTENTION", "P08", "40_hardware_attention", "Attention hardware-aware", "ESTABLISHED", [
        ("FLOP e movimento dei dati", "Lo stesso operatore può avere traffico di memoria molto diverso."),
        ("Tiling", "Blocchi di Q, K e V vengono elaborati nella memoria on-chip senza materializzare tutti gli score."),
        ("Softmax online", "Massimo, denominatore e numeratore vengono aggiornati blocco per blocco."),
        ("Backward e ricomputazione", "Salvare meno intermedi scambia memoria con compute aggiuntivo."),
        ("Backend", "FlashAttention, backend memory-efficient e math rispettano la stessa API entro tolleranze numeriche e condizioni diverse."),
    ]),
    (41, "CH-P08-LINEAR-ATTENTION", "P08", "41_linear_attention", "Linear attention, fast weights e delta rule", "ESTABLISHED", [
        ("Kernel fattorizzabile", "Una feature map permette di riassociare i prodotti senza una matrice completa di score."),
        ("Recurrence causale", "Statistiche S e z vengono aggiornate per token e hanno dimensione indipendente dalla lunghezza."),
        ("Normalizzazione", "Il denominatore controlla la scala e richiede feature e stabilizzazione coerenti."),
        ("Fast weights", "Lo stato può essere letto come memoria associativa che accumula coppie key-value."),
        ("Delta rule", "L'update corregge l'errore tra value desiderato e value recuperato, riducendo la sovrascrittura cieca."),
    ]),
    (42, "CH-P08-SEQUENCE-ALTERNATIVES", "P08", "42_sequence_alternatives", "State-space model, recurrence e long convolution", "ESTABLISHED", [
        ("State-space model", "Uno stato lineare ammette forma ricorrente e, in condizioni tempo-invarianti, forma convoluzionale."),
        ("S4", "Parametrizzazioni strutturate rendono gestibili kernel lunghi e dinamiche stabili."),
        ("Mamba", "Parametri selettivi dipendenti dall'input modificano lo stato mediante una scan hardware-aware."),
        ("Hyena e long convolution", "Kernel lunghi impliciti e gate collegano posizioni distanti senza score pairwise."),
        ("RWKV, RetNet, xLSTM e Griffin", "Recurrence moderne e ibridi usano stati e gate differenti; il confronto richiede budget e hardware equivalenti."),
    ]),
    (43, "CH-P08-HYBRID-MEMORY", "P08", "43_hybrid_memory", "Architetture ibride e memoria interna", "ESTABLISHED", [
        ("Ibridi tra layer", "Transformer, SSM e recurrence possono alternarsi con rapporti e interfacce dichiarati."),
        ("Attention locale e stato", "Una finestra precisa gestisce il vicino; uno stato compatto trasporta informazione oltre la finestra."),
        ("Memoria segmentale", "Stati di segmenti precedenti possono essere riusati o compressi con stop-gradient e capacità limitata."),
        ("Memoria associativa", "Key-value interne o moduli di memoria aggiornati online offrono accesso diverso dal residual stream."),
        ("Memoria interna ed esterna", "Lo stato neurale non coincide con retrieval documentale. Reset, isolamento e provenienza hanno contratti differenti."),
    ]),
    (44, "CH-P08-MOE-CONDITIONAL", "P08", "44_moe_conditional", "Mixture of Experts e calcolo condizionale", "CORE", [
        ("Router top-k", "Un router assegna probabilità agli esperti e attiva un sottoinsieme per token."),
        ("Capacità", "Ogni esperto riceve un limite di token. Overflow, rerouting o dropping devono essere dichiarati."),
        ("Load balancing", "Loss ausiliarie contrastano router collapse, ma possono competere con la specializzazione."),
        ("Expert parallelism", "Token ed output attraversano collective all-to-all tra dispositivi che ospitano esperti differenti."),
        ("Parametri totali e attivi", "Un MoE può avere molti parametri totali e pochi parametri attivi per token. FLOP, memoria e comunicazione vanno riportati separatamente."),
    ]),
    (45, "CH-P08-ALTERNATIVE-PREDICTION", "P08", "45_alternative_prediction", "Byte, predizione multi-token e language diffusion", "FRONTIER", [
        ("Byte e caratteri", "Modelli byte-level usano un vocabolario piccolo e sequenze più lunghe."),
        ("Gerarchie di byte", "Patch fisse o dinamiche riducono la lunghezza vista dal modello globale."),
        ("Predizione multi-token", "Head aggiuntive predicono più offset futuri e forniscono segnali oltre il token immediato."),
        ("Diffusione linguistica", "Processi continui, discreti o masked denoisano più posizioni attraverso step iterativi."),
        ("Assi separati", "Unità del testo, architettura e obiettivo di predizione sono scelte distinte che interagiscono."),
    ]),
]
