from __future__ import annotations

SPECS_P13_P14 = [
    (83, "CH-P13-EVAL-DESIGN", "P13", "83_eval_design", "Progettare una valutazione", "CORE", [
        ("Decisione e claim", "Una valutazione parte dalla decisione che deve sostenere. Il claim deve nominare popolazione, condizioni, metrica e incertezza."),
        ("Task e dataset", "Prompt, input, reference e rubric devono rappresentare l'uso previsto. Split e cutoff impediscono contaminazione intenzionale."),
        ("Metriche", "Metriche automatiche, giudizi umani e verificatori misurano proprietà differenti. Aggregazione e slice devono essere predefinite."),
        ("Giudici modello", "LLM-as-a-judge può scalare confronti, ma è sensibile a posizione, stile, modello e rubric. Serve calibrazione con giudizi indipendenti."),
        ("Report", "Intervalli, fallimenti, costi e limiti accompagnano il punteggio. Una leaderboard non sostituisce il protocollo."),
    ]),
    (84, "CH-P13-FACTUALITY", "P13", "84_factuality", "Fattualità, incertezza e affidabilità", "CORE", [
        ("Correttezza e supporto", "Una frase può essere vera senza essere sostenuta dal contesto fornito, oppure fedele al contesto ma riferita a una fonte errata."),
        ("Hallucination", "Il termine copre errori diversi: entità inventate, attribuzioni scorrette, contraddizioni e citazioni inesistenti. La tassonomia deve precedere la metrica."),
        ("Calibrazione", "Probabilità del token, score di un verifier e frequenza empirica devono essere collegati con un protocollo di calibrazione."),
        ("Astensione", "Un sistema può rifiutare o chiedere chiarimenti quando il rischio è alto. Coverage e accuracy conditional vanno riportate insieme."),
        ("Verifica e retrieval", "Fonti esterne possono aumentare supporto, ma retrieval e generazione hanno failure mode separati. La provenienza deve restare tracciabile."),
    ]),
    (85, "CH-P13-SYSTEM-EVAL", "P13", "85_system_eval", "Valutare contesto lungo, RAG, multimodalità e agenti", "CORE", [
        ("Contesto lungo", "Variare lunghezza, posizione dell'evidenza e distrattori misura utilizzo, non soltanto capacità nominale."),
        ("RAG", "Retrieval recall, context precision, attribution e risposta finale compongono una pipeline con errori localizzabili."),
        ("Multimodalità", "Modalità, risoluzione, sincronizzazione e grounding richiedono slice e metriche specifiche."),
        ("Agenti", "Successo, step, costo, side effect e recovery vengono misurati in ambienti versionati e resettabili."),
        ("Evaluation in production", "Shadow traffic, canary e monitoraggio collegano benchmark offline a distribuzioni reali senza confonderli."),
    ]),
    (86, "CH-P13-INTERPRETABILITY", "P13", "86_interpretability", "Interpretabilità delle rappresentazioni e dei circuiti", "CORE", [
        ("Oggetto dell'interpretazione", "Pesi, attivazioni, feature, head e comportamento sono livelli differenti. Il metodo deve dichiarare quale livello analizza."),
        ("Probing", "Un probe misura informazione decodificabile da una rappresentazione. Non prova che il modello usi quella informazione causalmente."),
        ("Attribution", "Gradienti, integrated gradients e perturbazioni assegnano importanza secondo definizioni differenti e possono essere instabili."),
        ("Causal intervention", "Ablation, activation patching e path patching modificano componenti e misurano effetti sul comportamento."),
        ("Circuiti", "Un circuito è un insieme di componenti e connessioni sufficienti per un comportamento nel setup studiato. Sufficienza e necessità richiedono test separati."),
    ]),
    (87, "CH-P13-SAE-CIRCUIT-TRACING", "P13", "87_sae_circuit_tracing", "Sparse autoencoder e interpretabilità scalabile", "ESTABLISHED", [
        ("Superposition", "Più feature possono condividere le stesse dimensioni di attivazione. La sparsità offre una ipotesi per separarle."),
        ("Sparse autoencoder", "Un encoder sovracompleto produce attivazioni sparse; un decoder ricostruisce il residual stream. Loss e sparsity coefficient determinano il dizionario."),
        ("Dead e splitting features", "Feature mai attive, troppo ampie o duplicate indicano problemi di training e granularità."),
        ("Circuit tracing", "Feature e attribution graph possono collegare input, computazione e output. Il grafo resta una approssimazione del calcolo completo."),
        ("Valutazione", "Interpretabilità automatica, causal intervention e coverage devono essere misurate. Una etichetta leggibile non prova monosemanticità universale."),
    ]),
    (88, "CH-P13-ROBUSTNESS-JAILBREAK", "P13", "88_robustness_jailbreak", "Robustezza, jailbreak e attacchi adversarial", "CORE", [
        ("Threat model", "Attaccante, accesso, obiettivo, budget e superficie definiscono il test. Un jailbreak testuale e un attacco ai pesi hanno contratti diversi."),
        ("Perturbazioni", "Typo, parafrasi, encoding e contenuti multimodali possono aggirare filtri superficiali."),
        ("Ottimizzazione adversarial", "Suffix e prompt vengono cercati per aumentare una loss di attacco. Trasferibilità e query budget devono essere riportati."),
        ("Difese", "Training, filtri, classificatori e refusal possono ridurre alcuni attacchi e introdurre falsi positivi o nuove bypass."),
        ("Valutazione adattiva", "Una difesa deve essere testata da attaccanti che conoscono il metodo, entro un protocollo sicuro e autorizzato."),
    ]),
    (89, "CH-P13-PROMPT-INJECTION", "P13", "89_prompt_injection", "Prompt injection e sicurezza dei tool", "CORE", [
        ("Istruzioni e dati", "Contenuti recuperati, pagine e documenti sono dati non fidati. Non devono acquisire automaticamente la priorità delle istruzioni di sistema."),
        ("Indirect prompt injection", "Una istruzione malevola può essere inserita in una fonte consultata dall'agente e attivarsi durante il retrieval o il browsing."),
        ("Tool mediation", "Policy esterne validano tool, argomenti e destinazioni. Il modello propone, ma l'enforcement avviene fuori dal testo generato."),
        ("Data exfiltration", "Segreti, memoria e risultati dei tool devono essere separati per scope. Output e URL possono diventare canali di esfiltrazione."),
        ("Test e incident response", "Canary, trace, allowlist, conferme e revoca delle credenziali supportano rilevamento, contenimento e recovery."),
    ]),
    (90, "CH-P13-SUPPLY-CHAIN-SECURITY", "P13", "90_supply_chain_security", "Poisoning, backdoor, extraction e supply chain", "CORE", [
        ("Data poisoning", "Campioni modificati possono alterare comportamento generale o target specifici. Provenienza e deduplicazione riducono alcune superfici."),
        ("Backdoor", "Un trigger induce un comportamento nascosto mantenendo prestazioni normali altrove. Scanner e fine-tuning non garantiscono rimozione."),
        ("Model extraction", "Query e output possono permettere di imitare capacità o recuperare informazioni. Rate limit e watermark comportamentali hanno limiti."),
        ("Artifact security", "Checkpoint, tokenizer, codice e dipendenze richiedono hash, firma, SBOM e policy di caricamento sicuro."),
        ("Repository e deployment", "File eseguibili, custom code e deserializzazione possono introdurre rischio indipendente dai pesi matematici."),
    ]),
    (91, "CH-P13-PRIVACY-FAIRNESS", "P13", "91_privacy_fairness", "Privacy, fairness e unlearning", "CORE", [
        ("Memorizzazione e leakage", "Un modello può riprodurre sequenze rare. Membership inference e extraction misurano rischi differenti."),
        ("Differential privacy", "DP limita l'influenza di un record mediante clipping e rumore, con parametri epsilon e delta e un costo di utilità."),
        ("Fairness", "Metriche di parità, equalized odds e calibration possono essere incompatibili sotto distribuzioni differenti. Il contesto decisionale guida la scelta."),
        ("Bias nei dati e nel sistema", "Rappresentazione, label, soglie e policy possono produrre disparità anche con lo stesso modello."),
        ("Machine unlearning", "Rimuovere l'influenza di dati richiede un criterio e una verifica. Cancellare un record dal corpus non modifica automaticamente il checkpoint."),
    ]),
    (92, "CH-P13-PROVENANCE", "P13", "92_provenance", "Watermarking e provenienza dei contenuti", "ESTABLISHED", [
        ("Provenienza crittografica", "Firma e manifest collegano un contenuto a un attore o a una catena di modifiche, se le chiavi e il workflow sono affidabili."),
        ("C2PA", "Credenziali di contenuto registrano asserzioni e ingredienti. Assenza di credenziali non prova che un contenuto sia sintetico."),
        ("Watermarking", "Un generatore può modulare token o segnali per consentire rilevamento statistico. Robustezza e falsi positivi dipendono dal canale."),
        ("Detection", "Classificatori di contenuto sintetico degradano sotto editing, nuovi modelli e shift. Un punteggio non è una prova forense isolata."),
        ("Policy e interfaccia", "Provenienza, disclosure e conservazione dei metadati devono essere progettate lungo la pipeline di pubblicazione."),
    ]),
    (93, "CH-P13-GOVERNANCE", "P13", "93_governance", "Diritto, governance e sostenibilità", "CORE", [
        ("Ruoli e responsabilità", "Owner, sviluppatore, deployer, utente e fornitore hanno controlli e informazioni differenti. Governance, accountability e comunicazione devono essere documentate."),
        ("Risk management", "NIST AI RMF organizza govern, map, measure e manage. Il framework guida un processo e non certifica automaticamente un sistema."),
        ("Norme e documentazione", "Obblighi dipendono da giurisdizione, ruolo e uso. Versione, data e parere legale devono essere separati dal testo tecnico stabile."),
        ("Incidenti e change management", "Segnalazione, classificazione, risposta e comunicazione collegano monitoraggio e governance."),
        ("Sostenibilità", "Energia, acqua, emissioni e ciclo di vita dell'hardware richiedono indicatori, baseline e confini di misura documentati."),
    ]),
    (94, "CH-P14-FOUNDATIONS-LAB", "P14", "94_foundations_lab", "Percorso pratico dai fondamenti", "CORE", [
        ("Ambiente riproducibile", "Python, dipendenze, seed e struttura del progetto vengono fissati prima degli esperimenti."),
        ("Dataset piccolo", "Un dataset controllabile permette di vedere preprocessing, split, batch e leakage."),
        ("Modello e loss", "Una baseline lineare precede la rete. Shape, logits e loss vengono verificati con test."),
        ("Training e valutazione", "Curve, checkpoint, validation e test seguono il protocollo costruito nel libro."),
        ("Report", "Il laboratorio produce README, output, figure e limiti, non soltanto un notebook che termina senza audit."),
    ]),
    (95, "CH-P14-SMALL-LM", "P14", "95_small_lm", "Costruire un piccolo language model", "CORE", [
        ("Corpus e tokenizer", "Un corpus ridotto e un tokenizer identificabile costruiscono sequenze e split verificabili."),
        ("Decoder Transformer", "Embedding, posizione, causal attention, MLP, norm e head di output vengono assemblati con test di shape."),
        ("Training", "AdamW, schedule, gradient clipping e checkpoint producono un run riproducibile su CPU o singola GPU."),
        ("Sampling", "Greedy, temperature e top-k mostrano la differenza tra distribuzione e traiettoria."),
        ("Limiti", "Un piccolo LM non rappresenta capacità o sicurezza di modelli su larga scala, ma rende osservabile l'intero contratto."),
    ]),
    (96, "CH-P14-PRODUCTION-PROJECT", "P14", "96_production_project", "Progetto di produzione completo", "CORE", [
        ("Definizione del problema", "Use case, utenti, output, autorizzazioni e costi degli errori precedono la scelta del modello."),
        ("Architettura", "Modello, retrieval, tool, storage e policy sono separati da interfacce e schemi."),
        ("Valutazione", "Dataset offline, test end-to-end, canary e monitoraggio coprono livelli differenti."),
        ("Deployment", "Versioni, secret, rollback, observability e incident response vengono esercitati prima del traffico reale."),
        ("Documentazione", "Model card, data card, runbook e decision log rendono il progetto revisionabile e aggiornabile."),
    ]),
    (97, "CH-P14-REPLICATION", "P14", "97_replication", "Riprodurre e leggere un paper", "CORE", [
        ("Domanda e claim", "Il paper viene scomposto in domanda, baseline, metodo, setup, risultati e limiti."),
        ("Artefatti", "Codice, checkpoint, dati e configurazioni vengono versionati e confrontati con la descrizione."),
        ("Replica", "Una riproduzione conferma lo stesso codice; una replica indipendente ricostruisce il metodo con scelte proprie."),
        ("Divergenze", "Differenze di hardware, seed, preprocessing e versioni vengono registrate invece di essere nascoste."),
        ("Conclusione sostenibile", "Il risultato viene limitato al setup eseguito e confrontato con l'incertezza del paper originale."),
    ]),
    (98, "CH-P14-FRONTIER-OBSERVATORY", "P14", "98_frontier_observatory", "Osservatorio della frontiera", "FRONTIER", [
        ("Scouting", "Nuovi paper, report e standard entrano in un registro con data, fonte e problema risolto."),
        ("Routing", "Ogni tecnica viene collocata nella parte proprietaria dell'oggetto modificato, senza creare una sezione generica della frontiera."),
        ("Maturità", "CORE, ESTABLISHED e FRONTIER descrivono evidenza e stabilità editoriale, non prestigio o popolarità."),
        ("Promozione", "Una tecnica cambia maturità dopo nuove repliche, adozione, standardizzazione o chiarimento dei limiti."),
        ("Edizioni", "Nuovi contenuti aggiornano catalogo, claim, capitoli e alias senza rinumerare identità stabili."),
    ]),
]

APPENDICES = [
    ("A_python_numpy_pytorch", "A", "Python, NumPy e PyTorch essenziali", ["tipi, collezioni e funzioni", "array e broadcasting", "tensor e device", "autograd e module", "debug e test"]),
    ("B_jax", "B", "JAX, compilazione e trasformazioni funzionali", ["array immutabili", "jit", "grad e vmap", "pmap e sharding", "confronto con PyTorch"]),
    ("C_formulario", "C", "Formulario matematico", ["algebra lineare", "calcolo", "probabilità", "informazione", "ottimizzazione"]),
    ("D_complessita", "D", "Complessità delle architetture", ["FLOP", "memoria", "attention", "recurrence e SSM", "serving"]),
    ("E_glossario", "E", "Glossario italiano-inglese", ["termini matematici", "training", "architetture", "inference", "sicurezza"]),
    ("F_dataset_benchmark", "F", "Dataset, benchmark e metriche", ["dataset card", "split", "benchmark", "metriche", "contaminazione"]),
    ("G_modelli_report", "G", "Schede di modelli e technical report", ["identità", "architettura", "dati", "post-training", "limiti"]),
    ("H_checklist", "H", "Checklist per riproducibilità, sicurezza e deployment", ["fonti", "test", "visuali", "sicurezza", "release"]),
    ("I_soluzioni", "I", "Soluzioni degli esercizi", ["metodo", "calcoli", "codice", "interpretazione", "limiti"]),
    ("J_cronologia", "J", "Cronologia dei paper fondamentali", ["simbolico", "reti neurali", "generativi", "Transformer", "foundation model"]),
    ("K_lettura_fonti", "K", "Guida alla lettura critica delle fonti", ["claim", "metodo", "setup", "risultato", "trasferibilità"]),
    ("L_edizioni_alias", "L", "Registro delle edizioni, degli alias e delle migrazioni", ["ID stabili", "alias", "split e merge", "redirect", "changelog"]),
]
