from __future__ import annotations

SPECS_P09_P10 = [
    (46, "CH-P09-SFT", "P09", "46_sft", "Supervised fine-tuning e instruction tuning", "CORE", [
        ("Dal pretraining alle istruzioni", "Il modello preaddestrato continua a ottimizzare una loss autoregressiva, ma i dati ora collegano richieste, contesto e risposte desiderate."),
        ("Formati conversazionali", "Ruoli, separatori, system message e loss mask definiscono quali token sono input e quali producono gradiente."),
        ("Instruction mixture", "Compiti e domini vengono mescolati con pesi espliciti. La quantità di esempi non coincide automaticamente con il loro contributo utile."),
        ("Teacher forcing e generalizzazione", "Durante il training il modello vede il prefisso corretto. La capacità di seguire istruzioni nuove deve essere valutata su template e domini separati."),
        ("Catastrophic forgetting e controllo", "Learning rate, durata e replay influenzano la perdita di capacità precedenti. Base model, modello SFT e sistema devono restare identificabili."),
    ]),
    (47, "CH-P09-PEFT", "P09", "47_peft", "Fine-tuning efficiente", "ESTABLISHED", [
        ("Parametri congelati e adattamento", "PEFT modifica un sottoinsieme di parametri o introduce moduli piccoli, lasciando invariata la maggior parte del checkpoint."),
        ("Adapter", "Blocchi bottleneck vengono inseriti nel percorso residuale. Posizione, dimensione e inizializzazione determinano l'interfaccia con il modello base."),
        ("LoRA", "Un aggiornamento di rango ridotto fattorizza la variazione di una matrice come BA e può essere fuso nei pesi per l'inference."),
        ("Prompt, prefix e IA3", "Soft prompt, prefix key-value e vettori di scaling modificano punti diversi del calcolo e non sono equivalenti."),
        ("QLoRA e compatibilità", "Il modello base quantizzato riduce memoria, mentre gli adapter restano addestrabili. Formato, tokenizer e architettura devono corrispondere."),
    ]),
    (48, "CH-P09-RLHF", "P09", "48_rlhf", "Preferenze, reward model e RLHF", "CORE", [
        ("Dalle dimostrazioni alle preferenze", "Dati di confronto ordinano risposte alla stessa richiesta. Il protocollo deve registrare istruzioni ai valutatori, accordo e slice."),
        ("Reward model", "Un modello assegna uno score alle risposte e viene addestrato con una loss di ranking. Lo score è una stima del dataset di preferenze, non una misura universale di qualità."),
        ("Policy optimization", "PPO o algoritmi affini aggiornano la policy per aumentare reward mantenendo un vincolo rispetto al modello di riferimento."),
        ("KL e reward hacking", "Il termine KL limita lo spostamento della policy. Un reward imperfetto può essere sfruttato senza migliorare l'obiettivo umano."),
        ("Valutazione e sicurezza", "Win rate, reward e giudizi automatici devono essere affiancati da controlli indipendenti, red teaming e analisi di regressione."),
    ]),
    (49, "CH-P09-PREFERENCE-OPT", "P09", "49_preference_opt", "Ottimizzazione diretta delle preferenze", "ESTABLISHED", [
        ("Evitare un reward model esplicito", "DPO riscrive un obiettivo di preferenza usando log-probability della policy e del riferimento, senza una fase PPO separata."),
        ("Coppie chosen e rejected", "Ogni esempio richiede la stessa condizione e due risposte confrontabili. Errori o stili spurii possono diventare scorciatoie."),
        ("Temperatura beta", "Beta controlla la forza relativa del vincolo rispetto al modello di riferimento e modifica i gradienti sulle coppie."),
        ("IPO, KTO, ORPO e varianti", "Le varianti cambiano assunzioni, forma della loss o tipo di feedback. I nomi non rendono gli obiettivi intercambiabili."),
        ("Offline preference data", "L'ottimizzazione resta limitata alla copertura del dataset. Nuove policy possono visitare risposte non rappresentate nelle coppie."),
    ]),
    (50, "CH-P09-SUPERVISION-VERIFIERS", "P09", "50_supervision_verifiers", "Process supervision, outcome supervision e verifier", "ESTABLISHED", [
        ("Supervisionare il risultato", "Outcome supervision assegna un segnale alla risposta finale e non localizza necessariamente il passaggio che ha prodotto l'errore."),
        ("Supervisionare il processo", "Process supervision etichetta passaggi intermedi. La validità dipende da come il processo viene reso osservabile e annotato."),
        ("Verifier", "Un verifier valuta candidate rispetto a un criterio. Può essere una regola, un esecutore, un modello o una combinazione."),
        ("Reward model di processo", "Punteggi per step possono guidare ricerca e training, ma possono introdurre preferenze per forme superficiali del ragionamento."),
        ("Goodhart e indipendenza", "Ottimizzare contro lo stesso verifier usato per la valutazione favorisce overfitting. Servono test e verificatori indipendenti."),
    ]),
    (51, "CH-P09-RLVR", "P09", "51_rlvr", "Reinforcement learning con reward verificabili", "ESTABLISHED", [
        ("Reward verificabile", "Problemi con risposta controllabile, come codice o matematica, consentono reward da test, parser o esecutori."),
        ("Rollout e gruppi", "La policy genera più soluzioni per la stessa richiesta. Il reward confronta traiettorie e costruisce advantage o ranking."),
        ("GRPO e policy update", "Algoritmi group-relative normalizzano reward all'interno di gruppi e aggiornano log-probability con vincoli di stabilità."),
        ("Sparse reward", "Un risultato finale corretto non identifica quali passaggi siano utili. Exploration, curriculum e shaping cambiano la densità del segnale."),
        ("Verificabilità limitata", "Un test incompleto può premiare exploit. Il reward verificabile è affidabile soltanto nel perimetro del verificatore."),
    ]),
    (52, "CH-P09-REASONING-TRAINING", "P09", "52_reasoning_training", "Addestrare e distillare il reasoning", "ESTABLISHED", [
        ("Tracce e risposte", "Una traccia di ragionamento è testo prodotto dal modello. Può aiutare il training senza costituire una prova fedele del processo interno."),
        ("Distillazione", "Un teacher produce soluzioni o distribuzioni che diventano target per uno student. Filtraggio e copertura stabiliscono cosa viene trasferito."),
        ("Self-consistency e rejection sampling", "Più candidate vengono generate e selezionate con voto o verifier. Il dataset risultante dipende dalla procedura di selezione."),
        ("Faithfulness", "Una spiegazione corretta può essere post-hoc. Valutare risposta e fedeltà richiede esperimenti differenti."),
        ("Costo e lunghezza", "Tracce più lunghe aumentano token e latenza. Il training deve distinguere utilità della risposta e budget del processo."),
    ]),
    (53, "CH-P09-TEST-TIME-COMPUTE", "P09", "53_test_time_compute", "Test-time compute, ricerca e controllo del budget", "ESTABLISHED", [
        ("Più compute dopo il training", "Il sistema può generare più candidate, approfondire una traiettoria o usare ricerca prima di restituire la risposta."),
        ("Best-of-n", "Un proposer genera n candidate e un verifier seleziona. Il beneficio dipende dalla diversità e dalla qualità del ranking."),
        ("Tree search", "Stati parziali vengono espansi, valutati e potati. Branching factor, profondità e budget definiscono il costo."),
        ("Adaptive compute", "Problemi differenti ricevono budget differenti secondo confidenza, difficoltà o policy. La stima di difficoltà può essere errata."),
        ("Metriche costo-qualità", "Accuracy o reward devono essere riportati insieme a token, forward, latenza e fallimenti del verifier."),
    ]),
    (54, "CH-P09-MODEL-UPDATE", "P09", "54_model_update", "Aggiornamento, merging ed editing del modello", "ESTABLISHED", [
        ("Continued adaptation", "Nuovi dati e obiettivi aggiornano il checkpoint. Replay, regolarizzazione e valutazioni controllano forgetting e regressioni."),
        ("Task arithmetic", "Differenze tra checkpoint possono essere combinate come vettori. La compatibilità richiede stessa base e corrispondenza dei parametri."),
        ("TIES e DARE", "Metodi di merging riducono interferenze mediante selezione, segni o sparsificazione. I risultati dipendono dai task e dalla scala dei delta."),
        ("Model editing", "ROME, MEMIT e famiglie affini cercano modifiche localizzate. Località, generalizzazione e side effect devono essere misurati separatamente."),
        ("Versioning e rollback", "Un update produce un nuovo artefatto con fonti, test e dipendenze. Merging ed editing non sostituiscono la gestione delle versioni."),
    ]),
    (55, "CH-P10-MULTIMODAL-FOUNDATIONS", "P10", "55_multimodal_foundations", "Fondamenti della multimodalità", "CORE", [
        ("Modalità e misure", "Testo, immagine, audio e azione hanno strutture e scale differenti. Ogni encoder produce una rappresentazione con assi dichiarati."),
        ("Allineamento", "Coppie sincronizzate o semanticamente collegate forniscono un segnale comune. Corrispondenza temporale e semantica non coincidono sempre."),
        ("Fusion", "Early, intermediate e late fusion combinano modalità in punti diversi e cambiano costo, dipendenze e disponibilità dei dati."),
        ("Missing modality", "Un sistema deve definire cosa accade quando una modalità è assente, corrotta o non autorizzata."),
        ("Valutazione", "Comprensione, retrieval, grounding e generazione richiedono benchmark distinti. Una media multimodale può nascondere una modalità debole."),
    ]),
    (56, "CH-P10-VLM", "P10", "56_vlm", "Vision encoder e Vision-Language Model", "CORE", [
        ("Patch e vision encoder", "Una immagine viene trasformata in patch o feature. Risoluzione, positional encoding e pooling definiscono la sequenza visiva."),
        ("Dual encoder", "CLIP allinea immagine e testo con una loss contrastiva. I due encoder supportano retrieval efficiente ma interagiscono tardi."),
        ("Projector", "Architetture modulari proiettano feature visive nella dimensione del language model. Il projector stabilisce capacità e numero di visual token."),
        ("Q-Former e cross-attention", "Query apprese possono estrarre un insieme compatto di feature. Altre architetture inseriscono cross-attention dedicata."),
        ("Grounding e hallucination", "Descrivere una immagine non garantisce localizzare oggetti o relazioni. Grounding, OCR e affidabilità richiedono test specifici."),
    ]),
    (57, "CH-P10-IMAGE-GENERATION", "P10", "57_image_generation", "Generazione e modifica delle immagini", "ESTABLISHED", [
        ("Latent diffusion", "Un autoencoder comprime l'immagine e il denoiser opera nello spazio latente. Il decoder ricostruisce pixel al termine."),
        ("Conditioning", "Testo, classi, immagini o mappe strutturali entrano attraverso cross-attention, concatenazione o moduli dedicati."),
        ("Classifier-free guidance", "Combinare predizioni condizionate e non condizionate aumenta aderenza, con un trade-off rispetto a diversità e saturazione."),
        ("Editing e inpainting", "Una mask stabilisce regioni modificabili. La coerenza con le aree conservate dipende da noise schedule e condition."),
        ("Controllo e provenienza", "ControlNet, adapter e reference image aggiungono vincoli. Dataset, diritti e metadati restano parte del sistema."),
    ]),
    (58, "CH-P10-NATIVE-MULTIMODAL", "P10", "58_native_multimodal", "Modelli multimodali nativi e any-to-any", "ESTABLISHED", [
        ("Token interleaved", "Sequenze possono alternare testo, immagini, audio e marker. Il tokenizer multimodale definisce unità e ordine."),
        ("Backbone condiviso", "Un Transformer può elaborare embedding di modalità differenti con parametri condivisi e adapter specifici."),
        ("Output multimodale", "La generazione di testo e media richiede head o decoder differenti, anche quando il backbone è comune."),
        ("Any-to-any", "Un'interfaccia generale deve dichiarare quali combinazioni di input e output sono state realmente addestrate e valutate."),
        ("Sincronizzazione", "Audio, video e testo possiedono frequenze differenti. Allineamento temporale e turn-taking diventano parte dell'architettura."),
    ]),
    (59, "CH-P10-AUDIO", "P10", "59_audio", "Audio, parlato e musica", "CORE", [
        ("Waveform e spettrogramma", "Il segnale audio è campionato nel tempo. STFT e mel filterbank producono rappresentazioni tempo-frequenza con parametri espliciti."),
        ("ASR", "Il riconoscimento vocale mappa audio a testo con obiettivi CTC, encoder-decoder o transducer. Streaming e offline hanno vincoli diversi."),
        ("TTS", "Sintesi vocale trasforma testo in acoustic representation e waveform. Durata, prosodia e vocoder sono componenti distinti."),
        ("Neural codec", "Codec neurali quantizzano il suono in code discreti multi-rate, usabili da audio language model."),
        ("Musica e dialogo", "Struttura musicale, speaker identity, turn-taking e latenza richiedono dati e metriche specifiche."),
    ]),
    (60, "CH-P10-VIDEO", "P10", "60_video", "Generazione video", "ESTABLISHED", [
        ("Spazio e tempo", "Un video aggiunge una dimensione temporale alle immagini. Token, patch o latent devono conservare movimento e identità."),
        ("Video diffusion", "Il denoiser opera su tensori spazio-temporali o latent compressi. Attention fattorizzata e convoluzioni riducono il costo."),
        ("Autoregressione", "Frame, patch o token video possono essere generati in ordine. L'ordine scelto modifica dipendenze e cache."),
        ("Coerenza", "Flicker, drift dell'identità e dinamiche impossibili richiedono controlli oltre la qualità di singoli frame."),
        ("Condizionamento e editing", "Testo, immagine iniziale, traiettoria o maschere guidano il video. Il controllo deve essere valutato nel tempo."),
    ]),
    (61, "CH-P10-SPATIAL-3D", "P10", "61_spatial_3d", "3D, spazio e rappresentazione delle scene", "ESTABLISHED", [
        ("Coordinate e camera", "Una scena 3D richiede sistemi di riferimento, intrinseci ed estrinseci della camera. Errori di coordinate cambiano il rendering."),
        ("NeRF", "Una funzione neurale mappa posizione e direzione a densità e colore. Volume rendering integra campioni lungo i raggi."),
        ("Gaussian splatting", "Gaussiane 3D con posizione, covarianza e colore vengono rasterizzate efficientemente da punti di vista nuovi."),
        ("Mesh, point cloud e voxel", "Rappresentazioni discrete offrono trade-off differenti tra topologia, memoria e rendering."),
        ("Generazione e grounding spaziale", "Testo e immagini possono condizionare scene, ma consistenza geometrica e fisica richiedono valutazioni dedicate."),
    ]),
    (62, "CH-P10-WORLD-EMBODIED", "P10", "62_world_embodied", "World model, embodied AI e vision-language-action", "ESTABLISHED", [
        ("Modello della dinamica", "Un world model predice stati, osservazioni o latent futuri dato lo stato corrente e un'azione."),
        ("Planning nel modello", "Traiettorie candidate vengono simulate e valutate prima di agire. Errori del modello possono essere sfruttati dal planner."),
        ("Embodied perception", "Un agente fisico collega camera, propriocezione, linguaggio e coordinate. Latenza e calibrazione influenzano ogni azione."),
        ("Vision-language-action", "VLA mappa osservazioni e istruzioni a token o controlli di azione. Frequenza e discretizzazione devono essere dichiarate."),
        ("Sicurezza e sim-to-real", "Simulazione, fallback, limiti di forza e supervisione umana riducono rischio, ma non eliminano mismatch con il mondo reale."),
    ]),
]
