from __future__ import annotations

SPECS_P11_P12 = [
    (63, "CH-P11-RETRIEVAL", "P11", "63_retrieval", "Information retrieval", "CORE", [
        ("Documenti, query e rilevanza", "Un sistema di retrieval ordina documenti rispetto a una query. La rilevanza dipende dal bisogno informativo e dalle label disponibili."),
        ("BM25", "La ricerca lessicale combina frequenza del termine, rarità nel corpus e normalizzazione della lunghezza. Tokenizzazione e campi modificano il punteggio."),
        ("Dense retrieval", "Un bi-encoder mappa query e documenti in vettori e usa una similarità. L'addestramento dipende da positivi, negativi e in-batch sampling."),
        ("Indici ANN", "Approximate nearest neighbor riduce il costo rispetto al confronto esaustivo. Recall, memoria e latenza dipendono dalla struttura e dai parametri."),
        ("Reranking", "Un cross-encoder valuta coppie query-documento con maggiore interazione, ma viene applicato a un insieme candidato più piccolo."),
    ]),
    (64, "CH-P11-RAG", "P11", "64_rag", "Retrieval-Augmented Generation", "CORE", [
        ("Una pipeline in due fasi", "Il retriever seleziona contesto esterno; il generatore produce la risposta condizionata sui documenti recuperati."),
        ("Chunking", "Dimensione, overlap e struttura dei chunk modificano recall e quantità di contesto. Un chunk non coincide sempre con una unità semantica."),
        ("Prompt con fonti", "Documenti, istruzioni e domanda devono avere confini espliciti. Il modello può ignorare, confondere o citare in modo scorretto il contesto."),
        ("Attribution", "Una risposta supportata deve essere collegabile a passaggi recuperati. Citazione presente e citazione corretta sono controlli differenti."),
        ("Valutazione end-to-end", "Recall del retriever, precisione del contesto, fedeltà e utilità della risposta devono essere misurate separatamente e insieme."),
    ]),
    (65, "CH-P11-ADVANCED-RAG", "P11", "65_advanced_rag", "RAG adattivo, correttivo e basato su grafi", "ESTABLISHED", [
        ("Query transformation", "Rewrite, expansion, decomposition e HyDE modificano la query prima del retrieval. Ogni trasformazione può migliorare recall o introdurre drift."),
        ("Retrieval adattivo", "Il sistema decide se recuperare, quante volte e con quale sorgente. La decisione è un componente da valutare, non un comportamento gratuito del modello."),
        ("Corrective RAG", "Documenti vengono valutati, filtrati o sostituiti prima della generazione. Confidence e web fallback richiedono soglie e autorizzazioni."),
        ("Graph RAG", "Entità, relazioni e comunità permettono query e sintesi multi-hop. Il grafo dipende da estrazione, normalizzazione e aggiornamento."),
        ("RAG agentico", "Un agente può pianificare retrieval successivi. Più step aumentano copertura e contemporaneamente costo, errori e superficie di attacco."),
    ]),
    (66, "CH-P11-CONTEXT-RETRIEVAL-MEMORY", "P11", "66_context_retrieval_memory", "Contesto lungo, retrieval e memoria", "ESTABLISHED", [
        ("Tre risorse differenti", "Contesto lungo, retrieval esterno e memoria persistente offrono capacità, costo e aggiornabilità differenti."),
        ("Quando usare il contesto", "Inserire tutti i documenti evita un indice separato ma aumenta prefill, distrattori e costo per richiesta."),
        ("Quando recuperare", "Retrieval seleziona un sottoinsieme aggiornabile e attribuibile. Può fallire per query, indice o ranking."),
        ("Memoria episodica", "Un sistema può salvare fatti o riassunti tra sessioni. Provenienza, consenso, scadenza e correzione diventano parte del contratto."),
        ("Routing ibrido", "Una policy può scegliere cache, contesto, retrieval o memoria. La decisione deve essere misurata rispetto a qualità, latenza e privacy."),
    ]),
    (67, "CH-P11-TOOLS", "P11", "67_tools", "Output strutturato e uso degli strumenti", "CORE", [
        ("Schema dell'output", "JSON Schema, grammar o tipi stabiliscono campi e vincoli. Validità sintattica non garantisce correttezza semantica."),
        ("Selezione del tool", "Il modello sceglie una funzione tra opzioni descritte. Nomi, descrizioni e autorizzazioni influenzano la decisione."),
        ("Argomenti", "Gli argomenti vengono estratti dal contesto e validati prima dell'esecuzione. Campi mancanti richiedono chiarimento o fallback."),
        ("Esecuzione e osservazione", "Il sistema esegue il tool fuori dal modello e restituisce un risultato strutturato. Timeout ed errori devono essere rappresentati."),
        ("Idempotenza e side effect", "Operazioni di lettura e scrittura hanno rischi differenti. Conferma, deduplicazione e transaction ID impediscono ripetizioni non desiderate."),
    ]),
    (68, "CH-P11-INTEROPERABILITY", "P11", "68_interoperability", "Protocolli e interoperabilità", "ESTABLISHED", [
        ("Contratti tra componenti", "Un protocollo definisce messaggi, capability, versioni ed errori tra modello, client, server e tool."),
        ("Model Context Protocol", "MCP organizza risorse, prompt e tool esposti da server. La versione della specifica e il trasporto devono essere dichiarati."),
        ("Agent-to-agent", "Protocolli A2A e famiglie affini descrivono discovery, task, messaggi e artefatti tra agenti."),
        ("Identità e autorizzazione", "Interoperabilità non implica fiducia. Token, scope, provenance e policy devono attraversare ogni hop."),
        ("Compatibilità ed evoluzione", "Version e capability negotiation rendono esplicita l'incompatibilità. Una versione non supportata non deve proseguire silenziosamente."),
    ]),
    (69, "CH-P11-AGENT-LOOP", "P11", "69_agent_loop", "Ciclo agentico, pianificazione e verifica", "CORE", [
        ("Osservare e aggiornare lo stato", "Un agente riceve input, risultato dei tool e memoria. Lo stato operativo deve essere separato dal testo libero del modello."),
        ("Pianificare", "Un piano scompone il compito in passi e dipendenze. Il piano iniziale può essere rivisto dopo nuove osservazioni."),
        ("Agire", "Ogni azione usa un tool o modifica un ambiente. Parametri, autorizzazioni e costo devono essere validati."),
        ("Verificare", "Test, controlli di stato o giudici indipendenti valutano il risultato. Una autocritica del modello non equivale a verifica esterna."),
        ("Terminare", "Budget, goal raggiunto, errore irreversibile o richiesta di approvazione definiscono condizioni di stop."),
    ]),
    (70, "CH-P11-AGENT-SYSTEMS", "P11", "70_agent_systems", "Multi-agent, browser, computer e code agents", "ESTABLISHED", [
        ("Browser agent", "L'agente interpreta pagine, link e form e deve distinguere contenuto della pagina da istruzioni autorizzate."),
        ("Computer use", "Screenshot, coordinate e azioni di input formano un loop percettivo. Risoluzione, focus e stato dell'interfaccia possono cambiare."),
        ("Code agent", "Repository, test, shell e diff definiscono l'ambiente. Modifiche devono essere limitate, testate e revisionabili."),
        ("Multi-agent", "Ruoli distinti possono parallelizzare o criticare, ma introducono comunicazione, ridondanza e propagazione degli errori."),
        ("Confronto con un singolo workflow", "Il beneficio deve essere misurato rispetto a una baseline con stesso modello, tool e budget."),
    ]),
    (71, "CH-P11-AGENT-TRAINING-EVAL", "P11", "71_agent_training_eval", "Training e valutazione degli agenti", "ESTABLISHED", [
        ("Traiettorie come dati", "Osservazioni, azioni, tool result e reward formano esempi sequenziali. Logging incompleto rende impossibile ricostruire il fallimento."),
        ("Imitation e SFT", "Traiettorie riuscite possono essere imitate. Il dataset deve includere recovery, errori e decisioni di non agire."),
        ("RL in ambienti", "Reward verificabili o simulati aggiornano policy multi-step. Il modello può sfruttare bug dell'ambiente o del checker."),
        ("Benchmark agentici", "Success rate, step, costo e side effect devono essere misurati. Task statici rischiano contaminazione e overfitting."),
        ("Evaluation harness", "Reset, seed, timeout, credenziali e versioni dei servizi sono parte del protocollo sperimentale."),
    ]),
    (72, "CH-P11-AGENT-SAFETY", "P11", "72_agent_safety", "Sicurezza operativa degli agenti", "CORE", [
        ("Least privilege", "Ogni tool riceve soltanto gli scope necessari. Credenziali e filesystem devono essere separati per task e tenant."),
        ("Sandbox", "Codice e browser vengono eseguiti in ambienti isolati con rete, processi e risorse limitate."),
        ("Human approval", "Azioni ad alto impatto richiedono conferma con anteprima, differenza e destinatario espliciti."),
        ("Rollback e audit", "Transaction log, snapshot e operazioni compensative permettono di ricostruire e correggere una traiettoria."),
        ("Prompt injection", "Contenuti esterni possono tentare di cambiare il piano. Dati non fidati e istruzioni di sistema devono restare separati."),
    ]),
    (73, "CH-P12-DISTILLATION-PRUNING", "P12", "73_distillation_pruning", "Distillazione e pruning", "CORE", [
        ("Teacher e student", "La distillazione usa logits, distribuzioni o sequenze del teacher come target aggiuntivi per uno student."),
        ("Temperature e loss", "Una temperatura più alta rivela relazioni tra classi o token. Hard target e soft target vengono pesati separatamente."),
        ("Sequence distillation", "Per modelli generativi, risposte del teacher diventano un nuovo dataset. Filtri e diversità determinano ciò che lo student vede."),
        ("Pruning", "Pesi, canali, head o layer possono essere rimossi. Sparsità nominale e accelerazione reale dipendono da kernel e hardware."),
        ("Recovery", "Fine-tuning o calibration recuperano qualità dopo compressione. Il confronto deve includere memoria, latency e regressioni per slice."),
    ]),
    (74, "CH-P12-QUANTIZATION", "P12", "74_quantization", "Quantizzazione", "CORE", [
        ("Scala e zero point", "Una mappa affine converte valori floating point in interi. La granularità per tensor o per channel cambia scale, errore e metadati."),
        ("PTQ", "Post-training quantization usa calibration senza riaddestrare completamente. La rappresentatività dei dati di calibration è essenziale."),
        ("QAT", "Quantization-aware training simula arrotondamento e clipping durante il training per adattare i pesi."),
        ("Weight-only e activation quantization", "Quantizzare soltanto i pesi riduce memoria; quantizzare attivazioni modifica anche i kernel di calcolo."),
        ("Metodi per LLM", "GPTQ, AWQ e SmoothQuant ottimizzano oggetti differenti: ricostruzione, canali salienti e outlier delle attivazioni. I loro contratti non sono intercambiabili."),
    ]),
    (75, "CH-P12-LOW-BIT-NATIVE", "P12", "75_low_bit_native", "Modelli low-bit nativi e co-design numerico", "FRONTIER", [
        ("Training nativo", "Un modello low-bit nativo incorpora il formato ridotto nella ricetta, invece di comprimere un checkpoint floating point al termine."),
        ("Pesi ternari e 1.58-bit", "BitNet b1.58 usa pesi in {-1,0,1} con attivazioni e scaling specifici. Il numero medio di bit non descrive da solo il kernel."),
        ("Straight-through estimator", "Operazioni discrete usano gradienti surrogati. La derivata applicata nel backward non è la derivata classica della quantizzazione."),
        ("Accumulazione", "Prodotti low-bit possono accumulare in precisione maggiore. Storage, compute e accumulator dtype devono essere separati."),
        ("Co-design hardware", "Il vantaggio richiede kernel, packing e unità aritmetiche che sfruttino il formato. Benchmark su hardware non ottimizzato possono nasconderlo."),
    ]),
    (76, "CH-P12-DECODING", "P12", "76_decoding", "Decoding e generazione vincolata", "CORE", [
        ("Greedy e beam search", "Greedy sceglie il massimo locale; beam mantiene più prefissi secondo score accumulati e criteri di lunghezza."),
        ("Sampling", "Temperature, top-k e top-p modificano la distribuzione prima dell'estrazione. Seed e backend influenzano la riproducibilità."),
        ("Penalità e stop", "Repetition penalty, stop sequence e minimum length intervengono in punti differenti e possono interagire."),
        ("Constrained decoding", "Grammar, automi e schema limitano i token ammessi. Validità strutturale non garantisce argomenti corretti."),
        ("Metriche", "Qualità, diversità, latency, token per secondo e probabilità della sequenza devono essere letti insieme."),
    ]),
    (77, "CH-P12-SPECULATIVE-DECODING", "P12", "77_speculative_decoding", "Speculative e parallel decoding", "ESTABLISHED", [
        ("Draft e target", "Un modello economico propone più token; il modello target li verifica in parallelo."),
        ("Acceptance", "La regola di accettazione conserva esattamente la distribuzione target nel metodo speculativo standard."),
        ("Speedup", "Il guadagno dipende da acceptance rate, costo del draft, lunghezza proposta e hardware."),
        ("Medusa, EAGLE e ReDrafter", "Head multiple, feature prediction e recurrent drafter producono candidate con strutture differenti."),
        ("Parallel decoding", "Metodi lookahead o Jacobi aggiornano più posizioni ma devono dichiarare se preservano esattamente la distribuzione originale."),
    ]),
    (78, "CH-P12-KV-CACHE", "P12", "78_kv_cache", "KV cache e riuso del contesto", "CORE", [
        ("Prefill e decode", "Il prefill calcola K e V per il prompt; il decode aggiunge una posizione e riusa la cache precedente."),
        ("Layout", "Layer, batch, KV head, token e head dimension determinano shape e byte. Contiguità e paginazione influenzano il kernel."),
        ("PagedAttention", "Blocchi logici vengono mappati a pagine fisiche per ridurre frammentazione e supportare sequenze di lunghezza diversa."),
        ("Prefix caching", "Prefissi identici possono condividere pagine se modello, tokenizer, adapter e messaggi sono compatibili."),
        ("Compressione ed eviction", "Quantizzazione, sliding window e selezione dei token riducono memoria, ma modificano precisione o contesto disponibile."),
    ]),
    (79, "CH-P12-SERVING", "P12", "79_serving", "Serving, batching e scheduling", "CORE", [
        ("Richieste eterogenee", "Prompt e output hanno lunghezze differenti. Un batch statico spreca slot quando alcune sequenze terminano."),
        ("Continuous batching", "Il scheduler inserisce nuove richieste tra iterazioni di decode e rimuove quelle concluse."),
        ("Throughput e latency", "Aumentare batch migliora utilizzo ma può aumentare time-to-first-token e inter-token latency."),
        ("Admission control", "Memoria KV, priorità, deadline e fairness determinano quali richieste entrano nel sistema."),
        ("Metriche di servizio", "TTFT, TPOT, goodput, queue time, error rate e costo devono essere osservati per tenant e classe di richiesta."),
    ]),
    (80, "CH-P12-DISTRIBUTED-INFERENCE", "P12", "80_distributed_inference", "Serving disaggregato e inference distribuita", "ESTABLISHED", [
        ("Tensor e pipeline parallelism", "Pesi e layer vengono divisi quando il modello non entra in un singolo dispositivo."),
        ("Expert parallelism", "MoE distribuisce esperti e usa all-to-all durante l'inference."),
        ("Prefill-decode disaggregation", "Cluster distinti ottimizzano prompt lunghi e generazione token-by-token, scambiando KV cache attraverso la rete."),
        ("Routing", "Modello, adapter, lunghezza e stato della cache guidano il placement. Spostare una richiesta può richiedere trasferimenti costosi."),
        ("Fault tolerance", "Replica, retry e idempotency devono evitare duplicazione degli output e perdita dello stato di sessione."),
    ]),
    (81, "CH-P12-COMPILERS-KERNELS", "P12", "81_compilers_kernels", "Compiler, kernel e runtime", "ESTABLISHED", [
        ("Grafo e operatori", "Un compiler cattura operazioni e dipendenze, poi applica fusion, scheduling e layout transformation."),
        ("Kernel fusion", "Combinare operazioni riduce lanci e traffico di memoria, ma può aumentare register pressure e ridurre riuso."),
        ("Triton e kernel custom", "Un linguaggio di kernel espone tiling e parallelismo mantenendo una astrazione più alta rispetto a CUDA."),
        ("torch.compile e graph break", "Tracing e guard permettono specializzazione dinamica. Python side effect o shape non supportate producono graph break."),
        ("Autotuning e portabilità", "Tile, num warps e schedule ottimali dipendono dall'hardware. Un kernel corretto richiede test numerici e benchmark separati."),
    ]),
    (82, "CH-P12-LLMOPS", "P12", "82_llmops", "LLMOps, edge, costo ed energia", "CORE", [
        ("Dalla versione al deployment", "Checkpoint, tokenizer, adapter, prompt e tool schema devono essere versionati come un'unica release di sistema."),
        ("Osservabilità", "Log, trace, metriche e feedback collegano input, modello, retrieval, tool e output senza esporre dati oltre il necessario."),
        ("Edge", "Dispositivi locali impongono memoria, batteria, termica e compatibilità dei kernel. Offline e privacy possono motivare il deployment locale."),
        ("Costo", "Costo per token, richiesta, utente e risultato utile sono metriche differenti. Cache e batching modificano l'allocazione."),
        ("Energia e sostenibilità", "Potenza, tempo, utilizzo hardware e mix energetico influenzano l'impatto. Stime devono dichiarare confini e metodologia."),
    ]),
]
